### PR TITLE
Add Windows style

### PR DESCRIPTION
**Pull request by lucienimmink**
Sorry for messing up the code styling :P

Not sorry for os="windows" by

- reversing flex-direction on `.hed`
- adding `os` attribute
- adding `.controls` instead of `.circle`
- adding SVG for `.controls`

### CODE REVIEW

**Comment by zachleat** [comment]
Can you swap the PR to tabs-based whitespace? Happy to merge after that!

**Comment by lucienimmink** [comment]
done. Also added a small editorconfig file to make sure everyone knows your preference for tabs :)

**Comment by zachleat** [comment]
Thank you!

**Comment by zachleat** [comment]
Shipping with 1.0.5!

**Pull request merged**
